name: Cinefy VOD Alert

on:
  workflow_dispatch:
  schedule:
  - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"

permissions:
  contents: write

jobs:
  check-vod:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Verificar Cinefy
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python check_cinefy.py

      - name: Salvar último VOD
        run: |
          if [ -f last_vod.json ]; then
            git config user.name "cinefy-bot"
            git config user.email "cinefy-bot@users.noreply.github.com"
            git add last_vod.json
            git diff --cached --quiet || git commit -m "Atualiza último VOD"
            git push
          fi
