name: Cinefy VOD Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-vod:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Verificar Cinefy
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python check_cinefy.py
